version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/demo/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 4
    versioning-strategy: "lockfile-only"
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "daily"
    open-pull-requests-limit: 4
    versioning-strategy: "lockfile-only"
