exclude: ^(pnpm-lock\.yaml)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@latest"
          - "typescript@latest"
          - "prettier-plugin-organize-imports@latest"
  - repo: local
    hooks:
      - id: readme
        name: Copy Readme
        entry: copy_readme.sh
        language: script
        pass_filenames: false
        types:
          - "markdown"
